export const data = [
	{
		company: null,
		industry: null,
		companyType: 'Startup',
		companySize: 'Very small with only about 3 developers',
		onboardingDuration: null,
		mentorProvided: null,
		experience:
			'I work for a very small start-up with only about 3 developers. The onboarding was pretty rough. I was given tickets to work on at first and when I ran into a blocker I would ask the lead for help and look over their shoulder to see what they did. I had to be really pro-active to seek help and request higher level jobs.',
		positiveOnboarding: false,
	},
	{
		company: 'Sprouts Farmers Market',
		industry: null,
		companyType: null,
		companySize: null,
		onboardingDuration: '1 week',
		mentorProvided: null,
		experience: `I work at Sprouts Farmers Market, a grocery store with about 350 locations in 20 states. On-boarding was 1 week of training, but my counterpart that had been there 10 years quit shortly after and not much of his knowledge was documented. So it was lots of figuring things out and documenting as I went so when they finally hired a new person I could just point them to all of the doc's I had been creating.`,
		positiveOnboarding: false,
	},
	{
		company: null,
		industry: null,
		companyType: 'Startup',
		companySize: null,
		onboardingDuration: '10 seconds',
		mentorProvided: null,
		experience: `at a fully remote start-up
    Onboarding? met the CEO for about 10 seconds sometime during the first week, given piecemeal access to everything as I tried to access that resource, a very brief high overview code tour, basically here are the four repos we work with
    Got the senior dev to show me something specific once, by asking to watch as he fixed an issue.
    so mostly, it’s catch as catch can, but if I didn’t ask, I’d certainly not get`,
		positiveOnboarding: false,
	},
	{
		company: null,
		industry: null,
		companyType: null,
		companySize: 'About 60 people',
		onboardingDuration: null,
		mentorProvided: null,
		experience: `mine was rushed due to them needing me right away. I drove 3 hours up to VA with the family to say high to the team and the decided to take that opportunity to give me my laptop and start me 3 weeks early remote. So I was working while trying to figure out all of the stuff I needed to move and where I was going to live. Honestly my onboarding experience was pretty horrible due to how quickly everything needed to happen. Once I was able to sit down for real with them they gave me a pretty big box full of swag and gift cards, nothing too fancy but it was a nice gesture as I've never had anything like that in any of my previous jobs. My company has been around for about 20 years but haven't done much growing within that time until recently. We're about 60 people and we just moved to a bigger building for expansion so not sure if we're at mid size company status yet.`,
		positiveOnboarding: false,
	},
	{
		company: 'Florida Blue',
		industry: null,
		companyType: null,
		companySize: null,
		onboardingDuration: '4 weeks',
		mentorProvided: null,
		experience: `Florida Blue had an interesting onboarding four weeks of waiting for access to repos, login info, etc and then cast into the fires.`,
		positiveOnboarding: false,
	},
	{
		company: 'Target',
		industry: null,
		companyType: null,
		companySize: null,
		onboardingDuration: null,
		mentorProvided: null,
		experience: `I work for Target and they have been great. They leave on boarding up to each team and my team is full of inspired people that are more than happy to help and give code reviews. They also let me pick which team I would join and in doing so I was allowed to choose my tech stack.`,
		positiveOnboarding: true,
	},
	{
		company: 'HubSpot',
		industry: null,
		companyType: null,
		companySize: null,
		onboardingDuration: null,
		mentorProvided: null,
		experience: `HubSpot did a couple weeks of corp/dept onboarding, which included a guided project to do w/ other new hires that goes over most of the stack. After that, my tech lead told me she didn’t expect anything of me for the 1st 6 mo’s, so to not feel dumb about asking any question.`,
		positiveOnboarding: true,
	},
	{
		company: 'CCMSI',
		industry: null,
		companyType: null,
		companySize: null,
		onboardingDuration: '1 month',
		mentorProvided: true,
		experience: `I work for CCMSI a company that is around 50 years old that specializes in handling workman comp claims. I was given a month of onboarding and attended an online class to learn the basics of Angular. They have started me out slow on assigning task and the mentorship from my team members has been excellent.`,
		positiveOnboarding: true,
	},
	{
		company: null,
		industry: null,
		companyType: null,
		companySize: 'large',
		onboardingDuration: '1 month',
		mentorProvided: true,
		experience: `I work at a large company and it's been pretty smooth. Before my start date they shipped my equipment. Logging into the company network was a quick phone call. I have a mentor that's been in my role for a year and I can literally ask her anything. Everything else has been very similar to Lambda: daily morning stand-ups via Slack calls, I have an onboarding manager similar to a labs TL. I'm part of a new hire group that's given time to learn the stack as well as business knowledge pretty much at our own pace since we're all from different backgrounds. When we're 'ready' we're put into our respective teams. It's been great.`,
		positiveOnboarding: true,
	},
];
